### ISSUE TITLE
RuntimeError: LaTeX was not able to process the following string: 'lp'

### ISSUE THREAD

**Issue by FelipeMuchtajidun** [dfm/daft#65]
Hello,This is the first time i use daft.Im trying to create one of the  example graphs in the web site  
%pylab inline
from IPython.external.mathjax import install_mathjax
from matplotlib import rc
rc("font", family="serif", size=12)
rc("text", usetex=True)

import daft

pgm = daft.PGM([3.6, 2.4], origin = [1.15, 0.8], node_ec="none")
pgm.add_node(daft.Node("cloudy", r"cloudy", 3, 3))
pgm.add_node(daft.Node("rain", r"rain", 2, 2))
pgm.add_node(daft.Node("sprinkler", r"sprinkler", 4, 2))
pgm.add_node(daft.Node("wet", r"grass wet", 3, 1))
pgm.add_edge("cloudy", "rain")
pgm.add_edge("cloudy", "sprinkler")
pgm.add_edge("rain", "wet")
pgm.add_edge("sprinkler", "wet")

pgm.render()
pgm.figure.savefig("mrf.pdf")

and i ma getting the error in the description.
Any help is much apreciated
Felipe

**Comment by Hemnepal** [comment]
My Script was working before, suddenly I got the same error. I spent almost an hour to find it and it did not help me at all. I closed the shell and run it again, then it worked. I don't know why there was a problem and when I close and reopen my spyder not book, it worked.

**Comment by davidwhogg** [comment]
That's bad. Should we close this bug for now?

**Comment by matanbz** [comment]
> Have you used LaTeX with matplotlib in the past? What happens if you remove the line:
> 
> ```
> rc("text", usetex=True)
> ```

Works.
To make sure there's no ambiguity I wrote:
rc("text", usetex=Fal=se)

**Comment by wkerzendorf** [comment]
It came back - the error. Just flagging this for other people trying to use cornerpy with latex.
