### ISSUE TITLE
Making rectangular (square) nodes

### ISSUE THREAD

**Issue by striatum** [dfm/daft#77]
Hello! I just ran onto daft and it looks amazing! Thanks a lot for the wonderful work!
Now, following Lee & Wagenmaker [book](http://bayesmodels.com/) I really consider quite informative to have a square nodes to discriminate discrete (categorical) variables from continuous (numerical) variables, which are then circular. Thus, I wonder how can I have both circular and square nodes? Also, I suppose shading vs. non-shading for observed vs. non-observed variables should be trivial.

Many thanks, again! PM

**Comment by striatum** [comment]
Please, anyone? Anything?

**Comment by davidwhogg** [comment]
I thought this got implemented; did it @dfm ?

**Comment by makokal** [comment]
I think #75 covered this and a pull request was already merged

**Comment by dkirkby** [comment]
It looks like #75 was never merged. Is this package still maintained?

**Comment by davidwhogg** [comment]
We are only barely maintained! I just merged that request. I haven't tested it. This is an open-source project and we welcome contributions (even if we are hella slow).
