### ISSUE TITLE
Edge pointing into a plate

### ISSUE THREAD

**Issue by j-faria** [dfm/daft#80]
I'm wondering how to create an Edge that points from a Node to a Plate. 
@eggplantbren did it so maybe he knows?

![simple pgm](https://cloud.githubusercontent.com/assets/1958991/10487624/bb81a802-728c-11e5-8649-3f03e5c895cd.png)
figure from http://arxiv.org/abs/1411.3921

**Comment by eggplantbren** [comment]
It's actually pointing to a node that I made completely transparent by
setting its alpha to zero. The source code is here
https://github.com/eggplantbren/RJObject/blob/master/Documents/Paper/pgm.py

On Wed, Oct 14, 2015 at 4:02 PM, João Faria <notifications@github.com>
wrote:

> I'm wondering how to create an Edge that points from a Node to a Plate.
> @eggplantbren <https://github.com/eggplantbren> did it so maybe he knows?
>
> [image: simple pgm]
> <https://cloud.githubusercontent.com/assets/1958991/10487624/bb81a802-728c-11e5-8649-3f03e5c895cd.png>
> figure from http://arxiv.org/abs/1411.3921
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dfm/daft/issues/80>.
>



-- 
Dr Brendon J. Brewer
Department of Statistics, The University of Auckland, New Zealand
Ph: +64 27 500 1336
Web: http://www.stat.auckland.ac.nz/~brewer/

**Comment by j-faria** [comment]
Thanks! 
I'll close the issue because there is a workaround.
