### ISSUE TITLE
Unable to bold some symbols?

### ISSUE THREAD

**Issue by ruzihao** [dfm/daft#83]
Hi, I am having a hard time to "bold" some symbols (represented as vector, rather than scalar), such as \mathbf{\mu}, etc.

Do you think it's an unknown issue? Thanks.

**Comment by dfm** [comment]
This is up to LaTeX. You'll need to use `boldsymbol` rather than `mathbf` since the latter only works for latin characters.

If it doesn't just work, you might need to include the `amsmath` package. Google around for how to include custom LaTeX packages in matplotlib because I can't actually remember how to do it... it's been a while!

**Comment by ruzihao** [comment]
Awesome! It works like a charm! Thanks Dan.

Let me attach the solution just in case other folks are looking for this.

1) Include amsmath package in matplotlib:

import matplotlib.pyplot as plt
params = {'text.latex.preamble' : [r'\usepackage{amsmath}']}
plt.rcParams.update(params)

2) Use \boldsymbol{}.

On Fri, Dec 11, 2015 at 2:27 PM, Dan Foreman-Mackey <
notifications@github.com> wrote:

> This is up to LaTeX. You'll need to use boldsymbol rather than mathbf
> since the latter only works for latin characters.
>
> If it doesn't just work, you might need to include the amsmath package.
> Google around for how to include custom LaTeX packages in matplotlib
> because I can't actually remember how to do it... it's been a while!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dfm/daft/issues/83#issuecomment-164026524>.
>



-- 
Best,
Hao Zhong
Ph.D. Student in Management (Information Technology)
Rutgers Business School

**Comment by ruzihao** [comment]
Awesome! It works like a charm! Thanks Dan.

Let me attach the solution just in case other folks are looking for this.

1) Include amsmath package in matplotlib:

import matplotlib.pyplot as plt
params = {'text.latex.preamble' : [r'\usepackage{amsmath}']}
plt.rcParams.update(params)

2) Use \boldsymbol{}.
