### ISSUE TITLE
bold greek letter

### ISSUE THREAD

**Issue by totucuong** [dfm/daft#96]
Hi everybody,

Is there a way to have a bold Greek letter for the name of a node. I tried 

`pgm.add_node(daft.Node('alpha', r'$\pmb{\alpha}$', 3, 3.5, fixed=True))`

But latex complaints:

RuntimeError: LaTeX was not able to process the following string:
b'$\\\\pmb{\\\\alpha}$'

Is there a way to indicate the latex package to use for Daft?

Thanks a lot!

**Comment by zobair5** [comment]
Try using amsmath and \boldsymbol:

`matplotlib.rc('text', usetex=True)`
`matplotlib.rcParams['text.latex.preamble']=[r"\usepackage{amsmath}"]`

`pgm.add_node(daft.Node('alpha', r'$\boldsymbol{\alpha}$', 3, 3.5, fixed=True)`

**Comment by davidwhogg** [comment]
+1

**Comment by totucuong** [comment]
Thanks @zobair5. It works great!
